// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Keepfit.DAL.Migrations
{
  [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class userAddPhotoPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userAddPhotoPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201502200653111_userAddPhotoPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
